[package]
name = "svea"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.21.2", features = ["full"] }
svea-http = { path = "../svea-http" }
futures = "0.3.24"
svea-filter = { path = "../svea-filter" }