[package]
name = "svea"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.21.2", features = ["full"] }
futures = "0.3.24"
svea-http = { path = "../svea-http" }
svea-filter = { path = "../svea-filter" }
svea-cookies = { path = "../svea-cookies" }
async-trait = "0.1.59"